<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PBUNDEGO-VCVU7" name="com.cisco.testscripts.ui.adminPortal.UserTest" tests="11" failures="0" timestamp="14 Sep 2019 13:11:48 GMT" time="0.001" errors="10">
  <testcase name="testUpdateUsers" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testUpdateUsers(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : UpdateUser in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testUpdateUsers(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : UpdateUser in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testUpdateUsers -->
  <testcase name="testassignUserToGroup" time="0.001" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testassignUserToGroup(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : AssignUserToGroupTest in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testassignUserToGroup(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : AssignUserToGroupTest in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testassignUserToGroup -->
  <testcase name="testSearchUser" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testSearchUser(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : SearchUserTest in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testSearchUser(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : SearchUserTest in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testSearchUser -->
  <testcase name="testcreateusernegativescenario" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testcreateusernegativescenario(java.util.Hashtable,org.testng.ITestContext) throws java.lang.Exception requires a @DataProvider named : testcreateusernegativescenario in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testcreateusernegativescenario(java.util.Hashtable,org.testng.ITestContext) throws java.lang.Exception requires a @DataProvider named : testcreateusernegativescenario in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testcreateusernegativescenario -->
  <testcase name="testVerifyAssignedUserAndLocation" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest"/>
  <testcase name="testDeleteUser" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testDeleteUser(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : DeleteUserTest in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testDeleteUser(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : DeleteUserTest in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testDeleteUser -->
  <testcase name="testCreateRegion" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testCreateRegion(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : CreateRegion in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testCreateRegion(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : CreateRegion in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testCreateRegion -->
  <testcase name="deleteRegionTest" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.deleteRegionTest(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : DeleteRegionTest in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.deleteRegionTest(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : DeleteRegionTest in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- deleteRegionTest -->
  <testcase name="updateRegionTest" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.updateRegionTest(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : UpdateRegion in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.updateRegionTest(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : UpdateRegion in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- updateRegionTest -->
  <testcase name="testassignLocationsToUser" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testassignLocationsToUser(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : AssignLocationsToUserTest in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testassignLocationsToUser(java.util.Hashtable,org.testng.ITestContext) throws java.lang.InterruptedException requires a @DataProvider named : AssignLocationsToUserTest in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testassignLocationsToUser -->
  <testcase name="testCreateUsers" time="0.000" classname="com.cisco.testscripts.ui.adminPortal.UserTest">
    <error type="org.testng.TestNGException" message="
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testCreateUsers(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : CreateUser in class com.cisco.base.DataProviderr">
      <![CDATA[org.testng.TestNGException: 
Method public void com.cisco.testscripts.ui.adminPortal.UserTest.testCreateUsers(java.util.Hashtable,org.testng.ITestContext) requires a @DataProvider named : CreateUser in class com.cisco.base.DataProviderr
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.cisco.base.main.main(main.java:118)
]]>
    </error>
  </testcase> <!-- testCreateUsers -->
</testsuite> <!-- com.cisco.testscripts.ui.adminPortal.UserTest -->
